/**
 * Cast of simulated LAN characters (dev only — not Forever-verified).
 */
export function createCast(realm = "LanRealm") {
  return [
    {
      key: "host",
      character: "Alex River",
      realm,
      class: "PRIEST",
      race: "Human",
      level: 8,
      guid: "Player-SIM-HOST",
      unit: "player",
      is_self: true,
      party_index: null,
      online: true,
      dead: false,
      zone: "Elwynn Forest",
      zone_source: "simulator",
      deaths: 0,
      deaths_pvp: 0,
      deaths_pve: 0,
      pvp_kills: 0,
      levels_gained: 0,
      dungeon_runs: 0,
    },
    {
      key: "sam",
      character: "Sam",
      realm,
      class: "ROGUE",
      race: "NightElf",
      level: 7,
      guid: "Player-SIM-SAM",
      unit: "party1",
      is_self: false,
      party_index: 1,
      online: true,
      dead: false,
      zone: "Elwynn Forest",
      zone_source: "simulator",
      deaths: 0,
      deaths_pvp: 0,
      deaths_pve: 0,
      pvp_kills: 0,
      levels_gained: 0,
      dungeon_runs: 0,
    },
    {
      key: "zmimz",
      character: "Zmimz",
      realm,
      class: "DRUID",
      race: "Tauren",
      level: 9,
      guid: "Player-SIM-ZMIMZ",
      unit: "party2",
      is_self: false,
      party_index: 2,
      online: true,
      dead: false,
      zone: "Mulgore",
      zone_source: "simulator",
      deaths: 0,
      deaths_pvp: 0,
      deaths_pve: 0,
      pvp_kills: 0,
      levels_gained: 0,
      dungeon_runs: 0,
    },
    {
      key: "jordan",
      character: "Jordan",
      realm,
      class: "HUNTER",
      race: "Dwarf",
      level: 6,
      guid: "Player-SIM-JORDAN",
      unit: "party3",
      is_self: false,
      party_index: 3,
      online: true,
      dead: false,
      zone: "Dun Morogh",
      zone_source: "simulator",
      deaths: 0,
      deaths_pvp: 0,
      deaths_pve: 0,
      pvp_kills: 0,
      levels_gained: 0,
      dungeon_runs: 0,
    },
  ];
}

export function cloneCast(cast) {
  return cast.map((p) => ({ ...p }));
}

export const ZONES = [
  "Elwynn Forest",
  "Westfall",
  "Redridge Mountains",
  "Duskwood",
  "Dun Morogh",
  "Loch Modan",
  "Wetlands",
  "Mulgore",
  "The Barrens",
  "Ashenvale",
  "Darkshore",
  "Silverpine Forest",
];

export const DUNGEONS = [
  "The Deadmines",
  "Wailing Caverns",
  "Shadowfang Keep",
  "The Stockade",
  "Blackfathom Deeps",
];
