# One-time: create foreverlan tunnel + ingest DNS + push-only config.yml (after tunnel login).
# Publishes your ingest hostname only. Board stays on http://127.0.0.1:8765/
#
# Set your real DNS name first, e.g.:
#   $env:FOREVERLAN_INGEST_HOSTNAME = "foreverlan-ingest.yourdomain.com"
# Or put ingestPublicHostname in repo-root config.json (gitignored).
$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $here
$exe = Join-Path $here "bin\cloudflared.exe"
if (-not (Test-Path $exe)) {
  Write-Host "Missing $exe"
  exit 1
}

function Resolve-IngestHostname {
  if ($env:FOREVERLAN_INGEST_HOSTNAME) { return $env:FOREVERLAN_INGEST_HOSTNAME.Trim() }
  $cfg = Join-Path $repoRoot "config.json"
  if (Test-Path $cfg) {
    try {
      $json = Get-Content $cfg -Raw | ConvertFrom-Json
      if ($json.ingestPublicHostname) { return [string]$json.ingestPublicHostname.Trim() }
    } catch {}
  }
  return "foreverlan-ingest.example.com"
}

$ingestHost = Resolve-IngestHostname
if ($ingestHost -like "*.example.com") {
  Write-Host "WARNING: using placeholder ingest host '$ingestHost'."
  Write-Host "Set FOREVERLAN_INGEST_HOSTNAME or config.json ingestPublicHostname before DNS/tunnel for a real domain."
}

$cert = Join-Path $env:USERPROFILE ".cloudflared\cert.pem"
if (-not (Test-Path $cert)) {
  Write-Host "Not logged in. Run: $exe tunnel login"
  exit 1
}

$list = & $exe tunnel list 2>&1 | Out-String
Write-Host $list

$uuid = $null
foreach ($line in ($list -split "`n")) {
  if ($line -match "foreverlan") {
    $m = [regex]::Match($line, "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
    if ($m.Success) { $uuid = $m.Value; break }
  }
}

if (-not $uuid) {
  Write-Host "Creating tunnel foreverlan..."
  $createOut = & $exe tunnel create foreverlan 2>&1 | Out-String
  Write-Host $createOut
  $m = [regex]::Match($createOut, "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
  if ($m.Success) { $uuid = $m.Value }
}

if (-not $uuid) {
  Write-Host "Could not determine tunnel UUID."
  exit 1
}

$cred = Join-Path $env:USERPROFILE ".cloudflared\$uuid.json"
if (-not (Test-Path $cred)) {
  Write-Host "Credentials file missing: $cred"
  exit 1
}

Write-Host "Routing DNS $ingestHost..."
& $exe tunnel route dns foreverlan $ingestHost 2>&1 | ForEach-Object { Write-Host $_ }

$configPath = Join-Path $here "config.yml"
$lines = @(
  "# Generated by setup-tunnel.ps1 - do not commit",
  "# Remote beta (push-only): only ingest is on the WAN.",
  "# Watch the board locally: http://127.0.0.1:8765/",
  "tunnel: $uuid",
  "credentials-file: $cred",
  "",
  "ingress:",
  "  - hostname: $ingestHost",
  "    service: http://127.0.0.1:8765",
  "  - service: http_status:404"
)
[System.IO.File]::WriteAllText($configPath, ($lines -join "`n") + "`n")

Write-Host ""
Write-Host "Wrote $configPath (ingest only → $ingestHost)"
Write-Host "Next: scripts\start-remote-beta.bat"
Write-Host "Optional remote board later: see access-policy.md (do not re-run this script for that)."
