# One-time: create foreverlan tunnel + ingest DNS + push-only config.yml (after tunnel login).
# Publishes foreverlan-ingest.example.com only. Board stays on http://127.0.0.1:8765/
$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$exe = Join-Path $here "bin\cloudflared.exe"
if (-not (Test-Path $exe)) {
  Write-Host "Missing $exe"
  exit 1
}

$cert = Join-Path $env:USERPROFILE ".cloudflared\cert.pem"
if (-not (Test-Path $cert)) {
  Write-Host "Not logged in. Run: $exe tunnel login"
  exit 1
}

$list = & $exe tunnel list 2>&1 | Out-String
Write-Host $list

$uuid = $null
foreach ($line in ($list -split "`n")) {
  if ($line -match "foreverlan") {
    $m = [regex]::Match($line, "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
    if ($m.Success) { $uuid = $m.Value; break }
  }
}

if (-not $uuid) {
  Write-Host "Creating tunnel foreverlan..."
  $createOut = & $exe tunnel create foreverlan 2>&1 | Out-String
  Write-Host $createOut
  $m = [regex]::Match($createOut, "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
  if ($m.Success) { $uuid = $m.Value }
}

if (-not $uuid) {
  Write-Host "Could not determine tunnel UUID."
  exit 1
}

$cred = Join-Path $env:USERPROFILE ".cloudflared\$uuid.json"
if (-not (Test-Path $cred)) {
  Write-Host "Credentials file missing: $cred"
  exit 1
}

Write-Host "Routing DNS foreverlan-ingest.example.com..."
& $exe tunnel route dns foreverlan foreverlan-ingest.example.com 2>&1 | ForEach-Object { Write-Host $_ }

$configPath = Join-Path $here "config.yml"
$lines = @(
  "# Generated by setup-tunnel.ps1 - do not commit",
  "# Remote beta (push-only): only ingest is on the WAN.",
  "# Watch the board locally: http://127.0.0.1:8765/",
  "tunnel: $uuid",
  "credentials-file: $cred",
  "",
  "ingress:",
  "  - hostname: foreverlan-ingest.example.com",
  "    service: http://127.0.0.1:8765",
  "  - service: http_status:404"
)
[System.IO.File]::WriteAllText($configPath, ($lines -join "`n") + "`n")

Write-Host ""
Write-Host "Wrote $configPath (ingest only)"
Write-Host "Next: scripts\start-remote-beta.bat"
Write-Host "Optional remote board later: see access-policy.md (do not re-run this script for that)."
